"""Library CRUD routes."""

import json
import logging

from database.connection import get_session
from dependencies import verify_token
from fastapi import APIRouter, Depends, HTTPException, Query, status
from schemas.libraries import (
    LibraryCreate,
    LibraryListResponse,
    LibraryResponse,
)
from services import library_service
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm import Session

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/libraries", tags=["Libraries"], dependencies=[Depends(verify_token)])


@router.post("", status_code=status.HTTP_201_CREATED, response_model=LibraryResponse)
async def create_library(
    body: LibraryCreate,
    db: Session = Depends(get_session),
) -> dict:
    """Create a new library.

    The ``id`` is generated by LAMB and passed in the request body.

    Args:
        body: Library creation payload.
        db: Database session.

    Returns:
        The created library.
    """
    try:
        lib = library_service.create_library(
            db,
            library_id=body.id,
            organization_id=body.organization_id,
            name=body.name,
            import_config=body.import_config,
        )
    except IntegrityError as exc:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="Library already exists or name is taken in this organization.",
        ) from exc

    return {
        "id": lib.id,
        "organization_id": lib.organization_id,
        "name": lib.name,
        "import_config": json.loads(lib.import_config) if lib.import_config else None,
        "item_count": 0,
        "created_at": lib.created_at,
    }


@router.get("/{lib_id}", response_model=LibraryResponse)
async def get_library(
    lib_id: str,
    db: Session = Depends(get_session),
) -> dict:
    """Get library details including item count.

    Args:
        lib_id: Library UUID.
        db: Database session.

    Returns:
        Library details.
    """
    result = library_service.get_library_with_item_count(db, lib_id)
    if result is None:
        raise HTTPException(status_code=404, detail="Library not found.")
    return result


@router.get("", response_model=LibraryListResponse)
async def list_libraries(
    organization_id: str = Query(..., description="Organization ID to filter by."),
    limit: int = Query(20, ge=1, le=100),
    offset: int = Query(0, ge=0),
    db: Session = Depends(get_session),
) -> dict:
    """List libraries for an organization.

    Args:
        organization_id: Filter by organization.
        limit: Max results.
        offset: Skip count.
        db: Database session.

    Returns:
        Paginated list of libraries.
    """
    libs, total = library_service.list_libraries(db, organization_id, limit, offset)
    return {"libraries": libs, "total": total}


@router.delete("/{lib_id}", status_code=status.HTTP_200_OK)
async def delete_library(
    lib_id: str,
    db: Session = Depends(get_session),
) -> dict:
    """Delete a library and all its content.

    LAMB is responsible for checking that no KB references this library's
    items before calling this endpoint.

    Args:
        lib_id: Library UUID.
        db: Database session.

    Returns:
        Confirmation message.
    """
    deleted = library_service.delete_library(db, lib_id)
    if not deleted:
        raise HTTPException(status_code=404, detail="Library not found.")
    return {"message": f"Library {lib_id} deleted."}


@router.get("/{lib_id}/import-config")
async def get_import_config(
    lib_id: str,
    db: Session = Depends(get_session),
) -> dict:
    """Get a library's current import configuration.

    Args:
        lib_id: Library UUID.
        db: Database session.

    Returns:
        The import config dict.
    """
    lib = library_service.get_library(db, lib_id)
    if lib is None:
        raise HTTPException(status_code=404, detail="Library not found.")
    return {
        "library_id": lib_id,
        "import_config": json.loads(lib.import_config) if lib.import_config else {},
    }


@router.put("/{lib_id}/import-config")
async def update_import_config(
    lib_id: str,
    config: dict,
    db: Session = Depends(get_session),
) -> dict:
    """Update a library's import configuration.

    Only affects future imports. Existing content is not re-processed.

    Args:
        lib_id: Library UUID.
        config: New import config.
        db: Database session.

    Returns:
        Updated config with a warning.
    """
    lib = library_service.update_import_config(db, lib_id, config)
    if lib is None:
        raise HTTPException(status_code=404, detail="Library not found.")
    return {
        "library_id": lib_id,
        "import_config": json.loads(lib.import_config) if lib.import_config else {},
        "warning": "This change only affects content imported from now on. "
                   "Existing content will not be re-processed.",
    }
