"""Pydantic schemas for library CRUD operations."""

from datetime import datetime
from typing import Any

from pydantic import BaseModel, Field

# --- Requests ---


class LibraryCreate(BaseModel):
    """Body for ``POST /libraries``."""

    id: str = Field(..., description="UUID generated by LAMB.")
    organization_id: str = Field(..., description="Owning organization ID.")
    name: str = Field(..., min_length=1, max_length=255, description="Library name.")
    import_config: dict[str, Any] | None = Field(
        None, description="Default import parameters for this library."
    )


class LibraryUpdate(BaseModel):
    """Body for ``PUT /libraries/{lib_id}`` (partial update)."""

    name: str | None = Field(None, min_length=1, max_length=255)
    import_config: dict[str, Any] | None = None


# --- Responses ---


class LibraryResponse(BaseModel):
    """Serialized library returned by the API."""

    id: str
    organization_id: str
    name: str
    import_config: dict[str, Any] | None = None
    item_count: int = 0
    created_at: datetime

    model_config = {"from_attributes": True}


class LibraryListResponse(BaseModel):
    """Paginated list of libraries."""

    libraries: list[LibraryResponse]
    total: int
