"""Business logic for library CRUD operations."""

import json
import logging
import shutil

from config import CONTENT_DIR
from database.models import ContentItem, Library, Organization
from sqlalchemy import func
from sqlalchemy.orm import Session

logger = logging.getLogger(__name__)


def ensure_organization(db: Session, org_id: str, name: str = "") -> Organization:
    """Get or create a lightweight organization record.

    The Library Manager keeps a minimal copy of the org for FK integrity.
    LAMB is the source of truth for organizations.

    Args:
        db: Database session.
        org_id: Organization ID from LAMB.
        name: Optional org name.

    Returns:
        The Organization row.
    """
    org = db.query(Organization).filter(Organization.id == org_id).first()
    if org is None:
        org = Organization(id=org_id, name=name or org_id)
        db.add(org)
        db.flush()
    return org


def create_library(
    db: Session,
    library_id: str,
    organization_id: str,
    name: str,
    import_config: dict | None = None,
) -> Library:
    """Create a new library.

    Args:
        db: Database session.
        library_id: UUID generated by LAMB.
        organization_id: Owning organization.
        name: Library name.
        import_config: Optional default import parameters.

    Returns:
        The created Library row.

    Raises:
        IntegrityError: If the library ID or (org, name) already exists.
    """
    ensure_organization(db, organization_id)

    lib = Library(
        id=library_id,
        organization_id=organization_id,
        name=name,
        import_config=json.dumps(import_config) if import_config else None,
    )
    db.add(lib)
    db.commit()
    db.refresh(lib)
    logger.info("Created library %s (%s) in org %s", library_id, name, organization_id)
    return lib


def get_library(db: Session, library_id: str) -> Library | None:
    """Fetch a library by ID.

    Args:
        db: Database session.
        library_id: Library UUID.

    Returns:
        Library row, or ``None`` if not found.
    """
    return db.query(Library).filter(Library.id == library_id).first()


def get_library_with_item_count(db: Session, library_id: str) -> dict | None:
    """Fetch a library with its item count.

    Args:
        db: Database session.
        library_id: Library UUID.

    Returns:
        Dict with library fields and ``item_count``, or ``None``.
    """
    lib = get_library(db, library_id)
    if lib is None:
        return None

    count = (
        db.query(func.count(ContentItem.id))
        .filter(ContentItem.library_id == library_id)
        .scalar()
    )

    return {
        "id": lib.id,
        "organization_id": lib.organization_id,
        "name": lib.name,
        "import_config": json.loads(lib.import_config) if lib.import_config else None,
        "item_count": count,
        "created_at": lib.created_at,
    }


def list_libraries(
    db: Session,
    organization_id: str,
    limit: int = 20,
    offset: int = 0,
) -> tuple[list[dict], int]:
    """List libraries for an organization with item counts.

    Args:
        db: Database session.
        organization_id: Filter by organization.
        limit: Max results.
        offset: Skip count.

    Returns:
        Tuple of (list of library dicts, total count).
    """
    query = db.query(Library).filter(Library.organization_id == organization_id)
    total = query.count()

    libs = query.order_by(Library.created_at.desc()).offset(offset).limit(limit).all()

    result = []
    for lib in libs:
        count = (
            db.query(func.count(ContentItem.id))
            .filter(ContentItem.library_id == lib.id)
            .scalar()
        )
        result.append({
            "id": lib.id,
            "organization_id": lib.organization_id,
            "name": lib.name,
            "import_config": json.loads(lib.import_config) if lib.import_config else None,
            "item_count": count,
            "created_at": lib.created_at,
        })

    return result, total


def delete_library(db: Session, library_id: str) -> bool:
    """Delete a library and all its content from disk and database.

    Args:
        db: Database session.
        library_id: Library UUID.

    Returns:
        ``True`` if deleted, ``False`` if not found.
    """
    lib = get_library(db, library_id)
    if lib is None:
        return False

    org_id = lib.organization_id

    # DB first, then disk — if crash occurs between, we lose files but DB is clean.
    # Cascade delete handles items and images in the database.
    db.delete(lib)
    db.commit()

    content_dir = CONTENT_DIR / org_id / library_id
    if content_dir.exists():
        shutil.rmtree(content_dir, ignore_errors=True)

    logger.info("Deleted library %s", library_id)
    return True


def update_import_config(
    db: Session, library_id: str, config: dict
) -> Library | None:
    """Update a library's default import configuration.

    Args:
        db: Database session.
        library_id: Library UUID.
        config: New import config dict.

    Returns:
        Updated Library row, or ``None`` if not found.
    """
    lib = get_library(db, library_id)
    if lib is None:
        return None

    lib.import_config = json.dumps(config)
    db.commit()
    db.refresh(lib)
    return lib
